# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-05 23:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='correo',
            field=models.CharField(default=datetime.datetime(2017, 4, 5, 23, 55, 51, 614424, tzinfo=utc), max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tiposdeservicio',
            name='imagen',
            field=models.ImageField(upload_to='services'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='imagen',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
